### ISSUE TITLE
Rename to `@react-native-community/peek-and-pop`

### ISSUE THREAD

**Issue by thymikee** [react-native-community/peek-and-pop#5]
Hey! 👋 

While this package is not released to the public, how about renaming it to: `@react-native-community/peek-and-pop`? So it corresponds nicely with other community libs.

If you think this is good idea, would be also nice to change the repo address to be https://github.com/react-native-community/peek-and-pop (without redundant react-native)

**Comment by osdnk** [comment]
dope

**Comment by osdnk** [comment]
@satya164 make me admin pls xD

**Comment by satya164** [comment]
![image](https://user-images.githubusercontent.com/1174278/60798272-207dc300-a171-11e9-8858-d92711990755.png)
